//MHX_DOMAIN

export const CLOUD_DOMAIN_NUMBER = 0;
export const SERVER28_DOMAIN_NUMBER = 1;

export const CLOUD_BASE_DOMAIN = "micehub-gov.com";
export const SERVER28_BASE_DOMAIN = "www.micehub.com";

export const DOMAIN_NUMBER_KEY = "MHX_DOMAIN_NUMBER";

//EXHIBITION
export const CLEAR_EXHIBITIONS = "CLEAR_EXHIBITIONS";
export const GET_EXHIBITIONS_REQUEST = "GET_EXHIBITIONS_REQUEST";
export const GET_EXHIBITIONS_SUCCESS = "GET_EXHIBITIONS_SUCCESS";
export const GET_EXHIBITIONS_FAIL = "GET_EXHIBITIONS_FAIL";
